[project]
name = "ml-flow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "importlib-metadata>=8.7.0",
    "mlflow>=3.1.1",
    "scikit-learn>=1.7.1",
]
